resources:
  repositories:
    - repository: templates
      type: github
      name: rdbartram/PSBuildRelease
      ref: refs/heads/master
      endpoint: rdbartram

Jobs:
  - template: Yaml Build Defintions/ModuleTest.yml@templates
    parameters:
      baseRepoId: rdbartram/StoragePre2K12
      baseBuildDefinitionId: 3
      pwsh: false
      coverageThreshold: 15
      moduleName: StoragePre2K12
